x-common-variables: &common-variables
  PYTHONUNBUFFERED: "yes"
  DISPATCHER_ENDPOINT: http://dispatcher:8111
  PLUGIN_EVENTS_URL: http://dispatcher:8111
  PLUGIN_DATA_URL: http://dispatcher:8111
  PLUGIN_MAX_FILE_SIZE: "100000000" # default limit of 100mb

services:
  unbox:
    image: docker.io/asdazul/plugin-unbox:11.1.0@sha256:7d8701d519ec17561254641432864ea2bfb05443e294a4d6af02b6a2d3adc440
    environment:
      <<: *common-variables
    networks:
      - azul

  entropy:
    image: docker.io/asdazul/plugin-entropy:11.1.0@sha256:946b8402ad2347a6d3369656064baaff78b4a2030b867b762e07172c6e3b2487
    environment:
      <<: *common-variables
      DISPATCHER_ENDPOINT: http://dispatcher:8111
    networks:
      - azul

  yara:
    image: docker.io/asdazul/plugin-yara:11.1.0@sha256:9841d31254807c4e493315e9c1474f2018f3cad2d84c809ae686f4473789d9e0
    environment:
      <<: *common-variables
      PLUGIN_NAME_SUFFIX: demo
      PLUGIN_SECURITY_OVERRIDE: OFFICIAL TLP:AMBER+STRICT
      PLUGIN_YARA_RULES_PATH: /yara_rules
      PLUGIN_MAX_FILE_SIZE: "10485760"
      PLUGIN_VERSION_SUFFIX: "9.0.0"
    volumes:
      - ./yara_rules:/yara_rules
    networks:
      - azul

networks:
  azul:
    name: azul_net
    external: true
