x-common-variables: &common-variables
  PYTHONUNBUFFERED: "yes"
  DISPATCHER_ENDPOINT: http://dispatcher:8111
  PLUGIN_EVENTS_URL: http://dispatcher:8111
  PLUGIN_DATA_URL: http://dispatcher:8111
  PLUGIN_MAX_FILE_SIZE: "100000000" # default limit of 100mb

services:
  unbox:
    image: docker.io/asdazul/plugin-unbox:10.0.0@sha256:30f00a9790123fa726df3bcece0ce41f95b4559efca30a3d6f0be891c99bd8a2
    environment:
      <<: *common-variables
    networks:
      - azul

  entropy:
    image: docker.io/asdazul/plugin-entropy:10.0.0@sha256:063187a461883cdbf3ea0bc85242ec86c26c3ee0dcd5897fa3cb591777a3868d
    environment:
      <<: *common-variables
      DISPATCHER_ENDPOINT: http://dispatcher:8111
    networks:
      - azul

  yara:
    image: docker.io/asdazul/plugin-yara:10.0.0@sha256:ad9f4bdf1704404d6aaff18db7aeed1d946024164eac3eaa41d0efb43b8800da
    environment:
      <<: *common-variables
      PLUGIN_NAME_SUFFIX: demo
      PLUGIN_SECURITY_OVERRIDE: OFFICIAL TLP:AMBER+STRICT
      PLUGIN_YARA_RULES_PATH: /yara_rules
      PLUGIN_MAX_FILE_SIZE: "10485760"
      PLUGIN_VERSION_SUFFIX: "9.0.0"
    volumes:
      - ./yara_rules:/yara_rules
    networks:
      - azul

networks:
  azul:
    name: azul_net
    external: true
